# permissions for end users to view agentsubscriptions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: agentsubscription-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: napa-operator
    app.kubernetes.io/part-of: napa-operator
    app.kubernetes.io/managed-by: kustomize
  name: agentsubscription-viewer-role
rules:
- apiGroups:
  - monitoring.cloud-native.ml
  resources:
  - agentsubscriptions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - monitoring.cloud-native.ml
  resources:
  - agentsubscriptions/status
  verbs:
  - get
