# permissions for end users to edit agentsubscriptions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: agentsubscription-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: napa-operator
    app.kubernetes.io/part-of: napa-operator
    app.kubernetes.io/managed-by: kustomize
  name: agentsubscription-editor-role
rules:
- apiGroups:
  - napa.cloud-native.ml
  resources:
  - agentsubscriptions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - napa.cloud-native.ml
  resources:
  - agentsubscriptions/status
  verbs:
  - get
