# permissions for end users to view sli.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: sli-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: napa-operator
    app.kubernetes.io/part-of: napa-operator
    app.kubernetes.io/managed-by: kustomize
  name: sli-viewer-role
rules:
- apiGroups:
  - openslo.cloud-native.ml
  resources:
  - sli
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - openslo.cloud-native.ml
  resources:
  - sli/status
  verbs:
  - get
