apiVersion: napa.cloud-native.ml/v1alpha1
kind: Agent
metadata:
  labels:
    app.kubernetes.io/name: agent
    app.kubernetes.io/instance: agent-sample
    app.kubernetes.io/part-of: napa-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: napa-operator
  name: agent-sample
spec:
  # TODO(user): Add fields here
