apiVersion: openslo.cloud-native.ml/v1alpha1
kind: SLO
metadata:
  labels:
    app.kubernetes.io/name: slo
    app.kubernetes.io/instance: slo-sample
    app.kubernetes.io/part-of: napa-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: napa-operator
  name: foo-slo
spec:
  service: service-sample
  indicator:
    metadata:
      name: foo-error
      displayName: Foo Error
    spec:
      ratioMetric:
        counter: true
        good:
          metricSource:
            type: Prometheus
            metricSourceRef: prometheus-datasource
            spec:
              query: sum(localhost_server_requests{code=~"2xx|3xx",host="*",instance="127.0.0.1:9090"})
        total:
          metricSource:
            type: Prometheus
            metricSourceRef: prometheus-datasource
            spec:
              query: localhost_server_requests{code="total",host="*",instance="127.0.0.1:9090"}
  objectives:
    - displayName: Foo Total Errors
      target: 0.98
