apiVersion: openslo.cloud-native.ml/v1alpha1
kind: SLO
metadata:
  labels:
    app.kubernetes.io/name: slo
    app.kubernetes.io/instance: slo-sample
    app.kubernetes.io/part-of: napa-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: napa-operator
  name: slo-sample
spec:
  # TODO(user): Add fields here
